### ISSUE TITLE
The `:session_key` option for `Cldr.Plug.SetLocale` is deprecated with no explanation

### ISSUE THREAD

**Issue by Hannes-Steffenhagen-bd** [elixir-cldr/cldr_plugs#2]
This option is apparently deprecated. But there's no explanation for why it is deprecated or what the plug expects you to do instead in either the message or the documentation (in fact, the documentation makes no mention of the option being deprecated).

Without this information the deprecation warning is essentially unactionable and therefore pointless.

**Comment by kipcole9** [comment]
Thank for the report and I agree with you, very unhelpful and objectionable without explanation.

I have added commit [c3bda6d](https://github.com/elixir-cldr/cldr_plugs/commit/c3bda6d677a73ebc9e7931fca8ab77446d0b528b) to improve the warning and update the documentation.

Would you consider reviewing the code to see if it addresses the issue?  If so I will publish a new release immediately.

**Comment by kipcole9** [comment]
I have published the updated docs which can be seen at [here](https://hexdocs.pm/ex_cldr_plugs/Cldr.Plug.SetLocale.html). Thanks for the report, much appreciated.
